### PR TITLE
GSREN3D-161: Arrow offset and update vcmap

### PR DESCRIPTION
**Pull request by ismailsunni**
### JIRA issue

https://jira.camptocamp.com/browse/GSREN3D-161

### Description

- Use the new offset feature
- Update vc map core and vcmap-cesium
- Update build and vite config
- Fix test by @toni-garcia-camptocamp 

### Screenshots

image

### CODE REVIEW

**Comment by ismailsunni** [comment]
hi @MaYohann or @toni-garcia-camptocamp since my test knowledge is limited, do you know why I got these failures?

```

 FAIL  src/components/__tests__/line/ThermometerStations.spec.ts [ src/components/__tests__/line/ThermometerStations.spec.ts ]
Error: cannot activate a single map
 ❯ MapCollection.setActiveMap node_modules/@vcmap/core/src/util/mapCollection.js:373:13
 ❯ RennesAppTest._setContextState node_modules/@vcmap/core/src/vcsApp.js:440:7
 ❯ async file:/home/isunni/dev/js/rennes3d-front/node_modules/@vcmap/core/src/vcsApp.js:468:9
 ❯ RennesAppTest._initializeMapToThermometerTest tests/RennesAppTest.ts:112:4
    110|     this._createContext()
    111|     if (this.test_context === null) return
    112|     await this.addContext(this.test_context)
       |    ^
    113|     await this._linkedFeaturesToLayer(RENNES_LAYER.trambusStops)
    114|     await this._linkedFeaturesToLayer(RENNES_LAYER.parking)
 ❯ async /home/isunni/dev/js/rennes3d-front/src/components/__tests__/line/ThermometerStations.spec.ts:20:1

```

**Comment by toni-garcia-camptocamp** [comment]
> hi @MaYohann or @toni-garcia-camptocamp since my test knowledge is limited, do you know why I got these failures?
> 
> ```
> 
>  FAIL  src/components/__tests__/line/ThermometerStations.spec.ts [ src/components/__tests__/line/ThermometerStations.spec.ts ]
> Error: cannot activate a single map
>  ❯ MapCollection.setActiveMap node_modules/@vcmap/core/src/util/mapCollection.js:373:13
>  ❯ RennesAppTest._setContextState node_modules/@vcmap/core/src/vcsApp.js:440:7
>  ❯ async file:/home/isunni/dev/js/rennes3d-front/node_modules/@vcmap/core/src/vcsApp.js:468:9
>  ❯ RennesAppTest._initializeMapToThermometerTest tests/RennesAppTest.ts:112:4
>     110|     this._createContext()
>     111|     if (this.test_context === null) return
>     112|     await this.addContext(this.test_context)
>        |    ^
>     113|     await this._linkedFeaturesToLayer(RENNES_LAYER.trambusStops)
>     114|     await this._linkedFeaturesToLayer(RENNES_LAYER.parking)
>  ❯ async /home/isunni/dev/js/rennes3d-front/src/components/__tests__/line/ThermometerStations.spec.ts:20:1
> ```

I tryed to find the problem but i didn't find, the bug come from the vcCore library. I sen an email to Ben and Jannes , your are on CC @ismailsunni

**Comment by toni-garcia-camptocamp** [comment]
@ismailsunni  The bug with test is fix

**Comment by ismailsunni** [comment]
Thanks, @toni-garcia-camptocamp! I didn't read the VCS team's email earlier :)

**Review by toni-garcia-camptocamp — COMMENTED** [review]
The offset of arrow is good, but i have bug on my local from the new config of vc system.
I put the screen of error bellow.
Maybe i don't have the good configuration or i forget something on my local ?
Thanks you

On page line 1 on 2D :
image

On page line 1 when i switch on 3D:
The line is not display: 
image

image

**Comment by ismailsunni** [comment]
@toni-garcia-camptocamp have you run `npm install` again?

**Comment by ismailsunni** [comment]
ah, it's actually related to the new structure of the package, but it should be handled by the proxy: https://github.com/sigrennesmetropole/cooperation_jn_trambus/pull/78/files#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR80

**Comment by ismailsunni** [comment]
hi @toni-garcia-camptocamp could you test it again? perhaps remove the whole `node_module` before running `npm i`. I even build it with docker, and it still works fine.

**Comment by toni-garcia-camptocamp** [comment]
@ismailsunni 
I have fix the problem on my local by replace '127.0.0.1' by 'localhost' in function , determineHostFromArgv
Every thing is good too me, i think you can merge it :)

**Pull request merged**
